### ISSUE TITLE
Tachiyomi

### ISSUE THREAD

**Issue by llkeji** [bauw2008/tv#1]
请问Tachiyomi如何安装oh插件，官方没有此插件啊

**Comment by bauw2008** [comment]
这个插件作者取消了没多久，安装也不能使用的。

**Comment by llkeji** [comment]
真可惜，爱看漫画维护也不咋样，还有木有推荐的漫画软件？

**Comment by bauw2008** [comment]
这类型app其实也有不少的，比如Cimoc、异次元，阅读、海阔。。。等。和现在的媒体软件都差不多，借个壳来放源。所以，有源你用m浏览器安装轻站都可以完美使用。不过现在这些壳我用过几款，除了Tachiyomi或改版的TachiJ2k干净点，其他的多多少少都有些广告之类，比如那个翻下菜单都能出现推广的。。。还有些已经到了广告比漫画还丰富的就不提了。国内这环境，你想要的只能说，能用就好了。
